###
###  before test, dont forget run GO_ENV=dev go run main.go
###

POST http://localhost:8080/signup HTTP/1.1
content-type: application/json

{
    "email": "user@hoge.com",
    "password": "testtest"
}

### ログイン

POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "user@hoge.com",
    "password": "testtest"
}

### ログアウト

POST http://localhost:8080/logout HTTP/1.1
content-type: application/json
